[project]
name = "Lift Journal Data"
requires-python = ">=3.10"
authors = [
    {name="Brandan Glendenning", email="brandan@glendigi.com"}
]
dependencies = [
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic",
    "email-validator"
]
